---
title: 'Earth Analytics Final Project: Phenocams'
author: "Kelsey Elwood"
date: "12/4/2017"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
knitr::opts_knit$set(root.dir = "/Users/elwoodk/Google_Drive/courses/earth-analytics/final-project/phenocam/RGB/") # set root directory
par(mfrow = c(1,1))
```

```{r load-libraries, message = FALSE}
library(phenopix)
library(jpeg)
library(rgdal) # seems to be necessary for `extractVIs` function, but Kelsey hasn't figured out why yet
library(zoo)
library(tseries)
library(reshape2)
library(strucchange)
library(ggplot2)
library(cowplot)
library(dplyr)
library(scales)
```

```{r setwd, eval = FALSE}
# To run the code in the console, set the working directory. To knit, do NOT set the working directory as the root directory should be set directly in the knitr options (code chunk #1)
setwd("/Users/elwoodk/Google_Drive/courses/earth-analytics/final-project/phenocam/RGB/")
```

```{r draw-ROI, eval = FALSE}
# To determine the region of interest (ROI) of the image, use the `DrawROI` function of the `phenopix` package. Click the vertices of the desired ROI. For macs, push the `esc` button on the keyboard to indicate when you are finished. This process only needs to be completed once.

DrawROI(path_img_ref = "REF/harvardlph_2016_07_15_120007.jpg", # the location of your reference image
        path_ROIs = "ROI/", # the path in your computer where to store RData with ROI properties
        nroi = 1, # number of ROIs
        roi.names = c("canopy"), # list of ROI names (in order)
        file.type = ".jpg" # the extention syntax of the reference file) 
```

```{r print-ROI}
# Load the ROI data
load('ROI/roi.data.Rdata')

# Show reference image with ROI superimposed on top
PrintROI(path_img_ref = 'REF/harvardlph_2016_07_15_120007.jpg',
         path_ROIs = 'ROI/',
         which = 'all',
         col = "white")
```

```{r extractVIs, eval = FALSE, cache=TRUE}
# To calculate the vegetation indices (VIs), use the following code. This process only needs to be done once. It takes between 10 and 30 minutes depending on the number of images and their quality (number of pixels in the image).
extractVIs(img.path = "IMG/", 
           roi.path = "ROI/", 
           vi.path = "VI/", 
           roi.name = "canopy", 
           plot = TRUE, # return a plot with R, G, and B indexes
           spatial = FALSE, # VI is averaged over the entire ROI (and not for each pixel individually)
           date.code = "yyyy_mm_dd_HHMM", # harvardlph date code structure embedded in file names
           npixels = 1,
           file.type = ".jpg", 
           bind = TRUE, 
           log.file = "VI/", 
           begin = NULL)
```


```{r filter-vi-data}
# Load the VI file created in `extractVIs`. The default name for the file is "VI.data"
load("VI/VI.data.Rdata")

VI_veg <- as.data.frame(VI.data$canopy) # To view as dataframe
filtered_VI <- autoFilter(data = unique(VI.data$canopy), 
                            dn=c('ri.av', 'gi.av', 'bi.av'), 
                            brt = 'bri.av', 
                            filter = c("night", "spline", "max"), 
                            na.fill = TRUE)

filtered_VI_df <- convert(filtered_VI, year='2016') %>% 
    mutate(DATE_POSIX = as.POSIXct(doy, format = "%Y-%m-%d"))

```

```{r write-filtered-csv, eval = FALSE}
write.csv(x = filtered_VI_df, 
          file = paste0(getwd(), "/VI/filtered_VI_df.csv"))

```

```{r plot-filtered_VI}
ggplot(data = filtered_VI_df, aes(x = DATE_POSIX, y = max.filtered)) +
    geom_point(color = "lightseagreen") +
    scale_x_datetime(name = "Date",
                     labels = date_format("%m/%d"), 
                     date_breaks = "2 weeks",
                     date_minor_breaks = "1 week") +
    ylab("Greenness Color Coordinate") + 
    theme_bw(base_size = 18) + 
    theme(axis.text.x = element_text(angle=45))

```

